### ISSUE TITLE
Can support for xlsm be added?

### ISSUE THREAD

**Issue by caffeinatedMike** [kz26/PyExcelerate#100]
I've been searching for a fast way to dump a large dataframe ([193014 rows x 165 columns]) to an xlsm file, but both `pandas` and `openpyxl` take at least an hour before finishing this task. I wondering if you'd consider adding support for xlsm files to this library. From what I've heard, there only needs to be one additional xml file generated for xlsm files to be opened and handled properly by Excel.

**Comment by kevmo314** [comment]
Yeah this seems reasonable. Probably just a different save function or flag there. I'm tight on bandwidth right now, a PR would be super welcome :) Otherwise, I'll look at adding this in the future.

**Comment by caffeinatedMike** [comment]
Awesome! I can try working on this tomorrow to see if I can manage something, but in the event I am unable to accomplish this on my own (as would be seen by a pull request) [here are the details](https://stackoverflow.com/a/28170939/2962937) that explain the extra file needed for `xlsm` files.

**Comment by caffeinatedMike** [comment]
@kevmo314 Pull Request sent :) Hope everything is in order. Sorry that I didn't add tests, I'm not familiar with the `nose` module and I didn't want to skew away from your formatting. Feel free to add tests as you see fit. From what I see, there aren't any performance degradations that I've noticed.
