### ISSUE TITLE
Error opening generated file with openpyxl

### ISSUE THREAD

**Issue by acGitUser** [kz26/PyExcelerate#34]
I have this  error:

Traceback (most recent call last):
  File "xlsError.py", line 13, in <module>
    wbr = openpyxl.reader.excel.load_workbook(filename=filename,use_iterators=True)
  File "D:\Software\WinPython-64bit-2.7.6.4\python-2.7.6.amd64\lib\site-packages\openpyxl\reader\excel.py", line 155, in load_workbook
    raise InvalidFileException(unicode(e))
openpyxl.exceptions.InvalidFileException: "There is no item named 'xl/styles.xml' in the archive"

while running this simple code: 
import openpyxl

from pyexcelerate import Workbook

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # data is a 2D array
filename = "output.xlsx"
sheetname = "test"

wb = Workbook()
wb.new_sheet(sheetname, data=data)
wb.save(filename)

wbr = openpyxl.reader.excel.load_workbook(filename=filename,use_iterators=True)
mySheet = wbr.get_sheet_by_name(sheetname)

**Comment by kevmo314** [comment]
It looks like this test is failing again, will follow up with openpyxl...

**Comment by kz26** [comment]
Issue opened with openpyxl: https://bitbucket.org/openpyxl/openpyxl/issues/553/cannot-read-xlsx-with-bare-stylesxml

**Comment by kz26** [comment]
Should be resolved per https://bitbucket.org/openpyxl/openpyxl/issues/544/formatted-workbook-doesnt-load
