### ISSUE TITLE
setting col width to autowidth results in ascii encoding issues

### ISSUE THREAD

**Issue by EmilyBarbour** [kz26/PyExcelerate#35]
receiving the standard, ascii cannot encode blah blah.  obviously my data has unicode chars

occurring in Worksheet.py in the below line when setting the value to str type.

    def get_col_xml_string(self, col):
    ....
            size = max((len(str(row[col])) * 7 + 5) / 7, size)

**Comment by kevmo314** [comment]
Issue should be fixed in the latest commit.
