### ISSUE TITLE
can I easily set the style of whole workbook or one sheet?

### ISSUE THREAD

**Issue by Zuckonit** [kz26/PyExcelerate#38]
seems I have to set the the style of cell one by one, is there an easy way to do this? or we can provide a interface to do this?

**Comment by Zuckonit** [comment]
like I just want to set the style "auto fit" to full workbook

**Comment by kevmo314** [comment]
does https://github.com/kz26/PyExcelerate#styling-ranges not work?

**Comment by Zuckonit** [comment]
sometimes, we don't care how many rows, cols of one sheet, can we easily use just like below:
```
workbook.set_style('balabala')
```
or 
```
worksheet.set_style('balabala')
```

**Comment by kevmo314** [comment]
not easily, no. I don't think the ECMA standard permits a default style like you're suggesting. manually adding the feature would also lead to problems for cells that don't have content, as how those are handled is ambiguous.

a more straightforward answer is that this can't be done in excel, thus it isn't something pyexcelerate can support. if you're looking to replicate the select all then apply style type of functionality, this is actually the equivalent of applying it over a range that spans the entire worksheet, and opening up the xlsx and checking the style definitions will verify this, so the correct way to do this in pyexcelerate is to select the range that contains all rows and all columns, and apply the styles accordingly.

**Comment by Zuckonit** [comment]
alright, I use pyexcelerate like below:
```
from pyexcelerate import Workbook

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # data is a 2D array

wb = Workbook()
wb.new_sheet("sheet name", data=data)
wb.save("output.xlsx")
```
and I am not sure the length of data, I want to make every row and col to be auto_fit,
how can I implement this? I didn't read all the source code, but I think we could provide an interface to set the default style (at least set before calling write function)

**Comment by kevmo314** [comment]
like I said, why not just select every column and every row? excel has a max row/column limit, so your data can't be larger than that anyways. if you want to add the paradigm of a default style, then just calculate the size of your data and manually apply the style that way.

in fact, your example is a good reason for why a default style paradigm *should not* be built into pyexcelerate. what should the fourth column look like? should it be autofit or not? it doesn't have data, so whether or not a default style applies to it is ambiguous. when you manually create the data in excel, you're forced to choose. because pyexcelerate aims to replicate excel's functionalities, the same applies here.

**Comment by Zuckonit** [comment]
actually the 'data' could be a generator, right? so we don't know the length of it. 
but you are right,  we can use some work around.
I would like to hack the source code(add a hook as I said).
thanks for your patience : -)

**Comment by kevmo314** [comment]
even if it's a generator, it has to be evaluated at some point by you, as pyexcelerate doesn't have any functionality for evaluating it. at that point, you can just calculate the appropriate size.

but barring that, if you really don't want to make any calculations on the size of the data, selecting the entire worksheet by selecting the encompassing range and applying that style is a viable option. a compromise may be to add an .all property, which returns a range containing the entire worksheet.
