### ISSUE TITLE
Performance of workbook.save for large files

### ISSUE THREAD

**Issue by mpbart** [kz26/PyExcelerate#39]
Is there any way to speed up the performance of calling workbook.save for large files (> 1,000,000 rows)? I'm seeing a significant amount of time spent in that function which seems to be because that's where all the data actually gets written into the xml files. Any ideas on ways I could possibly speed that up?

**Comment by kevmo314** [comment]
based on our load tests, the largest bottleneck is the write speed of the hard drive. we've spent a lot of time trying to optimize save() to be as fast as we can control. can you provide a sample xlsx output file and the amount of time required to produce it?

**Comment by mpbart** [comment]
I'm not sure how/where to upload files but it's a workbook that has 15 sheets with 5000 rows per sheet. Each row has 34 columns with each cell containing a string that's between 10 and 15 characters. Altogether that takes on the order of about 3.5 minutes or so which isn't too bad but that's just a sample of my data which is anywhere from 10-50x larger. Any ideas/help you can provide is much appreciated.

**Comment by kevmo314** [comment]
I'm having trouble replicating your results. here's my test code:

```
import pyexcelerate, time

def evaluate(target):
  wb = pyexcelerate.Workbook()
  for i in range(15):
    ws = wb.new_sheet("sheet %d" % i)
    for row in range(5000):
      for col in range(34):
        ws.set_cell_value(row, col, "abcdefghijklmnopqrstuvwxyz - %d - %d" % (row, col))
  wb.save(target)

start_time = time.time()
evaluate("[HDD PATH]/output.xlsx")
print("%s seconds on HDD" % (time.time() - start_time))

start_time = time.time()
evaluate("[SSD PATH]/output.xlsx")
print("%s seconds on SSD" % (time.time() - start_time))
```

I manually verified that this produces an xlsx file with 15 sheets of 5000 rows with 34 columns of at least 26 characters per cell, all unique. my results are as follows:

```
35.885748148 seconds on HDD
36.0273089409 seconds on SSD
```

extrapolating to 1M rows will take a substantial amount of time, but it's worth noting that that amounts to processing ~45GB of data at a rate of 6MB/s. what are the specifications of your computer and hard drive?

**Comment by kevmo314** [comment]
I found a few performance improvements, I'll push them to dev in a bit

**Comment by mpbart** [comment]
Ah it looks like a large part of the performance issues I was seeing is due to the styling that's being applied. I'm using `Style(size=-1)` as styling for all the columns which seems to be slowing it down considerably. Taking that out gives me roughly the same performance as you were getting. I should be able to work around this as I don't think its a big deal. Thanks for the help.

**Comment by kevmo314** [comment]
ah, okay, that makes sense. I'll take a look at some performance optimizations with the styles too, thanks for the feedback!
