### ISSUE TITLE
Strange behaviour of created xlsx

### ISSUE THREAD

**Issue by acGitUser** [kz26/PyExcelerate#44]
Hello, I use the following code to create a simple xlsx:

import pyexcelerate
wb = pyexcelerate.Workbook()
wb.new_sheet('sheet1', data=[['col11','col12','col13'],[1,2,3]])
wb.new_sheet('sheet2', data=[['col21','col22','col23'],['a','b','c']])
wb.save('bug.xlsx')

If I open the document and I change the data in the first sheet, the same cell is modified in the second sheet. This happens only if the change of the value is the first thing I do. If I change sheet before the change, Excel works properly.

**Comment by acGitUser** [comment]
Any news? Are you able to reproduce the issue?

**Comment by kevmo314** [comment]
I'm able to reproduce the issue, but I'm at a loss for why it's happening. I can't find anything wrong with the produced xml, so this seems to suggest that this might be a bug in Excel actually. Your observation that changing the sheet first fixes the issue supports that conclusion as well. I'm still trying to find a workaround, but I'm not sure if there's an easy fix.

**Comment by acGitUser** [comment]
It seems that for excel both sheet are selected, so all action in excel are performed on all sheets: you can see in the title bar [GROUP] after the filename, and when you change sheet this word disappear. Maybe the library have to set the first sheet as current or active in order to remove the group selection. I hope this explanation is readable and will help you.

**Comment by kevmo314** [comment]
Hmm, I'll take a look at that, that sounds like a plausible explanation.

**Comment by kevmo314** [comment]
I think your explanation is correct, but I'm having difficulty finding where the active sheet is set in the ECMA specifications. It's probably there, just not sure where. I think it'll be faster to reverse engineer it, I'll try to get this fixed soon.

**Comment by hanstzalora** [comment]
I can't reproduce the issue with Excel 2016 Mac OS X.

**Comment by hanstzalora** [comment]
@kevmo314 I believe I know what causing the problem.

Line 4 in `templates/xl/worksheets/sheet.xml` is the culprit:
`<sheetView tabSelected="1" workbookViewId="0">`

Using bug.xlsx based on the code given by @acGitUser above, I uncompressed the file and remove `tabSelected="1"` attribute from sheetView tag in `xl/worksheets/sheet2.xml` and compressed back to get the modified xlsx file. As a result, Only one sheet is active, and changing value in sheet 1 does not affect value in sheet 2. 

I think, `tabSelected="1"` is the way to tell Excel which sheets are active. So, if you put them on all sheets, then it means all sheets are active. Hence, changing cell A1 in sheet 2 will affect all sheets.

Therefore, I would suggest two things: Firstly, remove `tabSelected="1"` attribute in the sheet template. And secondly, only apply this attribute to the first sheet after you generate all the sheets. In this way, we only have first sheet that is active.

**Comment by acGitUser** [comment]
As suggested by @hanstzalora, I've changed the file templates\xl\worksheets\sheet.xml removing the attribute tabSelected and it works! (it works also setting tabSelected="0"). Is it possible to update the distribution? My collegues are waiting for this fix!

**Comment by hanstzalora** [comment]
@acGitUser you can just edit `sheet.xml` in your `pyexcelerate` package if you need it ASAP.

**Comment by kevmo314** [comment]
Huh, I thought I had tried that, but if it works for you then we'll merge that in :)

**Comment by kz26** [comment]
Latest changes pushed to dev - waiting to hear about a bugfix from the openpyxl project before pushing 0.6.8.

**Comment by kevmo314** [comment]
openpyxl test seems to have been passing for a while so we'll release this soon.
