### ISSUE TITLE
`import __version__` in `setup.py` breaks dependency processing

### ISSUE THREAD

**Issue by jnm** [kz26/PyExcelerate#52]
Hello,

Beginning with 0.7.0, I cannot install PyExcelerate in a fresh virtualenv without manually installing `six` or `Jinja2` first. I believe that `from pyexcelerate.version import __version__` in `setup.py` fails unless these dependencies are already installed, and therefore `pip` cannot process the package at all.

    $ virtualenv /tmp/e
    New python executable in /tmp/e/bin/python
    Installing setuptools, pip...done.
    $ . /tmp/e/bin/activate
    (e)$ pip install --upgrade pip
    Downloading/unpacking pip from https://pypi.python.org/packages/9c/32/004ce0852e0a127f07f358b715015763273799bd798956fa930814b60f39/pip-8.1.2-py2.py3-none-any.whl#md5=0570520434c5b600d89ec95393b2650b
      Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
    Installing collected packages: pip
      Found existing installation: pip 1.5.4
        Uninstalling pip:
          Successfully uninstalled pip
    Successfully installed pip
    Cleaning up...
    (e)$ pip install PyExcelerate
    Collecting PyExcelerate
      Using cached PyExcelerate-0.7.0.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-dF77PW/PyExcelerate/setup.py", line 4, in <module>
            from pyexcelerate.version import __version__
          File "pyexcelerate/__init__.py", line 1, in <module>
            from .Workbook import Workbook
          File "pyexcelerate/Workbook.py", line 1, in <module>
            from . import Worksheet
          File "pyexcelerate/Worksheet.py", line 1, in <module>
            from . import Panes
          File "pyexcelerate/Panes.py", line 1, in <module>
            from . import Range
          File "pyexcelerate/Range.py", line 1, in <module>
            from . import DataTypes
          File "pyexcelerate/DataTypes.py", line 3, in <module>
            import six
        ImportError: No module named six
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dF77PW/PyExcelerate/
    (e)$ 

The older, hard-coded `version` string in `setup.py` still works fine for me:

    (e)$ pip install PyExcelerate==0.6.7
    Collecting PyExcelerate==0.6.7
    /tmp/e/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
      SNIMissingWarning
    /tmp/e/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
      InsecurePlatformWarning
      Downloading PyExcelerate-0.6.7-py2.py3-none-any.whl
    Collecting Jinja2 (from PyExcelerate==0.6.7)
      Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
        100% |████████████████████████████████| 266kB 1.4MB/s 
    Collecting six>=1.4.0 (from PyExcelerate==0.6.7)
      Downloading six-1.10.0-py2.py3-none-any.whl
    Collecting MarkupSafe (from Jinja2->PyExcelerate==0.6.7)
      Downloading MarkupSafe-0.23.tar.gz
    Installing collected packages: MarkupSafe, Jinja2, six, PyExcelerate
      Running setup.py install for MarkupSafe ... done
    Successfully installed Jinja2-2.8 MarkupSafe-0.23 PyExcelerate-0.6.7 six-1.10.0
    (e)$

**Comment by kz26** [comment]
Whoops, didn't realize that broke new installs. I've reverted it to use hardcoded version strings in setup.py for version 0.7.1, which should now be live on PyPI and the master branch.
