### ISSUE TITLE
Is " hook-pyexcelerate.Writer.py"   old?

### ISSUE THREAD

**Issue by kazumaro756** [kz26/PyExcelerate#58]
Thank you for developers effort.
Let me ask one question.

I wonder The file" hook-pyexcelerate.Writer.py" is not available for latest version of Pyinstaller.
For example,  "PyInstaller.hooks.hookutils" was changed to "PyInstaller.utils.hooks".

Please updata " hook-pyexcelerate.Writer.py" file.

**Comment by kz26** [comment]
Hi, can you explain what you mean by this? The PyExcelerate hook appears to be present in the latest PyInstaller 3.3 release: https://github.com/pyinstaller/pyinstaller/blob/master/PyInstaller/hooks/hook-pyexcelerate.Writer.py

**Comment by kazumaro756** [comment]
Thank you for your comment,kz26!

First,I have tried the hook file that you mention.
https://github.com/pyinstaller/pyinstaller/blob/master/PyInstaller/hooks/hook-pyexcelerate.Writer.py

But my Pyinstaller cant read "hook-pyexcelerate.Writer.py" file.
When Pyinstaller strat to read "hook-pyexcelerate.Writer.py", I got "FileNotFoundError" saying  

> Path or glob"C:\Users......\pyexcelerate\templates\[Content_Types].xml"not found or matches no files.

So, I wonder the hook file of pyinstaller is not correct,and try old one, but did not work too.
old one : https://github.com/kz26/PyExcelerate/blob/dev/hook-pyexcelerate.Writer.py.

I use python3.5 and both pyinstaller and pyexcelerate are latest version.

Is this the problem caused by my environment or, pyexcerate hook file?
If you think my environment is problem,please say so. I will close this Issue.
If not, please check 
https://github.com/pyinstaller/pyinstaller/blob/master/PyInstaller/hooks/hook-pyexcelerate.Writer.py

**Comment by kazumaro756** [comment]
I am so sorry!
I checked "pip list --o" , and I noticed my pyinstaller is not latest version!
After update pyinstaller, Buiding exe completed successfully.
Thank you for you comment!

And I must say, pyexceraleta is great!
It cuts down the time that processing excel file(especially writing process!!).

Thank you so much!

**Comment by kz26** [comment]
No problem, glad to hear that you were able to solve the problem.
