### ISSUE TITLE
Timezone-unaware inner date

### ISSUE THREAD

**Issue by riparian-imakedonsky** [kz26/PyExcelerate#59]
PyExcelerate doesn't work for timezone-aware datetimes.
Error is raised when you pass some timezone-aware datetime to be written.

This forces users to coerce their datetimes to strings first or delete related timezone info before write.

Error place is there
```python
@staticmethod
	def to_excel_date(d):
		if isinstance(d, datetime):
			delta = d - DataTypes.EXCEL_BASE_DATE
			excel_date = delta.days + (float(delta.seconds) + float(delta.microseconds) / 1E6) / (60 * 60 * 24) + 1
			return excel_date + (excel_date > 59)
		elif isinstance(d, date):
			# this is why python sucks >.<
			return DataTypes.to_excel_date(datetime(*(d.timetuple()[:6])))
		elif isinstance(d, time):
			return DataTypes.to_excel_date(datetime(*(DataTypes.EXCEL_BASE_DATE.timetuple()[:3]), hour=d.hour, minute=d.minute, second=d.second, microsecond=d.microsecond)) - 1
```

http://joxi.ru/GrqGQdTQ7NXE2z.png

**Comment by kevmo314** [comment]
Can you post a code sample to reproduce the error you're seeing?

**Comment by riparian-imakedonsky** [comment]
```python
from datetime import datetime, timezone
from pyexcelerate import Workbook

timezone_aware_datetime = datetime.now(tz=timezone.utc)

wb = Workbook()
wb.new_sheet('random', data=[[timezone_aware_datetime]])
wb.save('sample.xlsx')
```

That's probably simplest possible sample to reproduce that issue.
But generally speaking, whenever this package encounters timezone-aware datetime/time - it's behaving same way.

**Comment by kevmo314** [comment]
Thanks, I've submitted a fix to automatically strip the time zone info with a warning, as Excel does not support time zones.

**Comment by riparian-imakedonsky** [comment]
Thanks
