### ISSUE TITLE
New Feature Request: Hyperlink support

### ISSUE THREAD

**Issue by ddhingra1991** [kz26/PyExcelerate#61]
Is there hyperlink support present in PyExcelerate ? like in openpyxl : [https://openpyxl.readthedocs.io/en/latest/_modules/openpyxl/worksheet/hyperlink.html#Hyperlink] ?

**Comment by kevmo314** [comment]
There's not currently, however we can probably add this. I can take a look.

**Comment by kevmo314** [comment]
Looking into this more, what's the difference between a hyperlink and the `HYPERLINK()` function found [here](https://support.office.com/en-us/article/hyperlink-function-333c7ce6-c5ae-4164-9c47-7de9b76f577f)? PyExcelerate should have support for formulas if you just set the value to `=HYPERLINK(...)`, does this accomplish your goal?

**Comment by suyash248** [comment]
@kevmo314 I've tried to use `=HYPERLINK(...)` function to add a hyperlink in a particular cell in my excel sheet. But I'm facing [this](urlhttps://github.com/kz26/PyExcelerate/issues/63 issue. Could you please help me out.

Thanks

**Comment by kevmo314** [comment]
Since #63 is fixed, you should be able to create a hyperlink via `=HYPERLINK(...)` correctly in the latest dev version.

**Comment by suyash248** [comment]
Thanks, @kevmo314. How would I use `latest dev` using `pip`?

**Comment by suyash248** [comment]
I ended up using latest `dev` as follows - 

`pip install -e git://github.com/kz26/PyExcelerate.git@be38e3cfcea5aad9ddc83b8f456adea0f8507841#egg=PyExcelerate
`
Now formulas are working as expected. Thank a lot @kevmo314 👍

**Comment by kevmo314** [comment]
Great to hear! We'll push an update to master soon so it'll be reflected on the pip version as well.
