### ISSUE TITLE
Formula not working

### ISSUE THREAD

**Issue by suyash248** [kz26/PyExcelerate#63]
I'm trying to use HYPERLINK formula as follows - 

`ws.set_cell_value(1, 1, '=HYPERLINK("www.someurl.com", "Click here")')
`

But when I look at the underlying cell(1, 1) in excel file, it complains that formula is invalid. Actually pyexcelerate prepends an additional `=` sign, so above formula is translated to - 

> ==HYPERLINK("www.someurl.com", "Click here")

I also tried to use the formula without `=` sign as follows -

`ws.set_cell_value(1, 1, 'HYPERLINK("www.someurl.com", "Click here")')
`

So in this is case excel client complains that that formula is invalid, it's because there is no `=` sign, so above formula is translated to - 

> HYPERLINK("www.someurl.com", "Click here")

valid formula must contain only one `=` sign in the cell, e.g. 
> =HYPERLINK("www.someurl.com", "Click here")     #This is valid

**Comment by kevmo314** [comment]
Which version of python and Excel are you using? Doing

```
ws.set_cell_value(1, 1, '=HYPERLINK("http://www.google.com", "Click here")')
```

works correctly for me and opens Google when I click on the cell with Excel 2016.

**Comment by kevmo314** [comment]
Also, do other formulas work? eg

```
ws.set_cell_value(1, 3, '=SUM(A1, B1)')

**Comment by suyash248** [comment]
Hi @kevmo314,

I'm facing the similar issue with other formulas as well. I'm using Python 3.6 and I've tried to open `xls` file using `Numbers(on mac os)` & google sheets, excel file is getting opened but the hyperlink is invalid.

**Comment by kevmo314** [comment]
Interesting, sounds like we might be mismatching the spec by accident, but Excel coerces it to a valid hyperlink. I'll take a look later tonight.

**Comment by kevmo314** [comment]
Fixed in the latest dev version, indeed Excel seems to be more lenient in parsing formulas that don't match the spec exactly.

**Comment by suyash248** [comment]
It would be convenient if you could merge this fix to `master`.
