### ISSUE TITLE
Hyper Link is not working

### ISSUE THREAD

**Issue by sanjusci** [kz26/PyExcelerate#64]
When I am Using hyperlink formula as below:

sheet.set_cell_value(3, 3, '=HYPERLINK("https://abc.com/download", "Download File")')

In the excel file showing formula is invalid because It's adding 1 more (=) equal, Formula in excel sheet as below:

==HYPERLINK("https://abc.com/download", "Download File")
means It's adding additional (=) equals. When I am using formula without (=) equal 

sheet.set_cell_value(3, 3, 'HYPERLINK("https://abc.com/download", "Download File")')

In the excel file showing formula is invalid.

HYPERLINK("https://abc.com/download", "Download File")

The valid link should be as below:
=HYPERLINK("https://abc.com/download", "Download File")

Please check and fix it.

**Comment by kevmo314** [comment]
This is fixed in the latest dev version, see #61
