### ISSUE TITLE
"There is no item named '[Content_Types].xml' in the archive" Error in Openpyxl.

### ISSUE THREAD

**Issue by sunbarve** [kz26/PyExcelerate#71]
Getting above while read xlsx file using load_workbook(filename, data_only=True)

**Comment by defaultgnome** [comment]
Hey ho, I got the same problem when working with `openpyxl` and I found out that the problem was that I created a new `.odf` file (with LibreOffice) and renamed it to `.xlsx`. This was the mistake - I needed to convert the odf to an Execl format to solve it.
Hope this help.

**Comment by cmayea** [comment]
> Hey ho, I got the same problem when working with `openpyxl` and I found out that the problem was that I created a new `.odf` file (with LibreOffice) and renamed it to `.xlsx`. This was the mistake - I needed to convert the odf to an Execl format to solve it. Hope this help.

It solve the problem for me! Thanks a lot

**Comment by blendajazi** [comment]
Hi i got the same problem. But in my case im on a mac and dont have Microsoft products installed.
I just created a .xlsx file. When trying to push my dataframe to excel i get this error. 
Is there a possibility to make a workaround without using MS Products directly on Mac?
