### ISSUE TITLE
I can't import excel

### ISSUE THREAD

**Issue by Whpitot** [kz26/PyExcelerate#75]
when I export data to excel , i get a exception as follow: 

File "/usr/lib/python2.7/site-packages/pyexcelerate/Worksheet.py", line 265, in get_xml_data
 row_data.append(self.__get_cell_data(cell, x, y, style))
 File "/usr/lib/python2.7/site-packages/pyexcelerate/Worksheet.py", line 197, in __get_cell_data
return "<c r=\"%s%s" % (Range.Range.coordinate_to_string((x, y)), z)
 UnboundLocalError: local variable 'z' referenced before assignment

**Comment by kevmo314** [comment]
Do you have a code sample to reproduce the issue?

**Comment by Whpitot** [comment]
I have solved this issue.

I debug the source code(Worksheet.py, line 197). I found one of the value in cells is
 {"pay_mode":"到付（客户承担）","consignee":"","insurance_money":"0.00","is_insured":"B"}

The type of value is not support in type = DataTypes.get_type(cell) (Worksheet.py, ine 176)

so, I can't get the value of z, this throw a exception as above mentioned.

can you understand me?

**Comment by kevmo314** [comment]
I've addressed this in fcd0d7a6d9b995ee89e2dc7ce01caf9eaed308d0.
