### ISSUE TITLE
Filter out special chars, that excel cannot handle.

### ISSUE THREAD

**Issue by vmatt** [kz26/PyExcelerate#77]
In my dataset there are two characters, that sql can handle, but excel is not.
\u001a
\u001c

The error message:"Replaced Part: /xl/worksheets/sheet1.xml part with XML error.  Illegal xml character. Line 11, column 2386."

My proposal would be, that we should replace this chars with "", or "?", and do a console warning, because these characters broke the file.

**Comment by kevmo314** [comment]
I've addressed this in a15d085cc62f028a769cfe8977b130141c45ca9e, thanks for the report.
