### ISSUE TITLE
LargeZipFile exception for huge file creation

### ISSUE THREAD

**Issue by marioSigel** [kz26/PyExcelerate#80]
Creation of huge files (excel file size 135MB) causes a LargeZipFile exception for me: 
LargeZipFile: Filesize would require ZIP64 extensions

I could solve that by adding allowZip64=True parameter to following line:

https://github.com/kz26/PyExcelerate/blob/d39b05307bbc80c83b4140822305bf8976396d97/pyexcelerate/Writer.py#L45

Is it possible to set an attribute/add a parameter somewhere (e.g. Workbook, Workbook.save ) to allow 64-bit usage (maybe in a future release)?

**Comment by kevmo314** [comment]
There was a similar feature request to add the compression mode as an arg, I think it's reasonable to pass `*args` and `**kwargs` to `ZipFile()` here. I'll make such a change.

A change-less solution though, it looks like python 3 defaults to `allowZip64=True`, if it's an option you could also do that.
