### ISSUE TITLE
Supports 3.7 python?

### ISSUE THREAD

**Issue by simkimsia** [kz26/PyExcelerate#83]
Will you add python 3.7 support?

https://github.com/kz26/PyExcelerate/blob/dev/setup.py#L41

**Comment by kevmo314** [comment]
Sure, I've marked 3.7 as supported. There shouldn't be any compatibility issues besides it not being tagged, do you run into any issues installing it?

**Comment by simkimsia** [comment]
So far so good. Thanks :)
