### ISSUE TITLE
Prevent dates from being treated as formula

### ISSUE THREAD

**Issue by ylhsieh** [kz26/PyExcelerate#85]
Hi, I am wondering if there is a way to keep strings like "1980/12/1" intact. Now it is being treated as a formula. Is there a way to set the DataType of a column to text? Thanks!

**Comment by kevmo314** [comment]
Do you have an example to reproduce? We don't actually do any date type checking and explicitly mark string values as text, so this is a little surprising.

**Comment by ylhsieh** [comment]
Hi, thanks for your quick reply! I later found out it was coming from the source xls file, not PyExcelerate. I am reading in an xls file and writing to a new file. Sorry for my mistake...
