### ISSUE TITLE
Trailing/leading spaces are trimmed from cells

### ISSUE THREAD

**Issue by bbies** [kz26/PyExcelerate#86]
If you save a cell with value " hi " it will be displayed in Excel as "hi". Is there a way to set style or save parameters to preserve all spaces?

**Comment by kevmo314** [comment]
I don't think we do any postprocessing of the strings, this sounds like something that excel is doing. I'll try and take a look...

**Comment by Leon14451** [comment]
To keep spaces, you should set `xml:space` attribute of start-tag `t`.

**Comment by kevmo314** [comment]
Thanks, I've added this to the dev branch.
