### ISSUE TITLE
Handling Special Characters (Unicode) 

### ISSUE THREAD

**Issue by vaebhav** [kz26/PyExcelerate#88]
I have had multiple data sets that had special characters at various parts.

Due to this the end dump always throws an error for Illegal Character.

I propose the special characters can be filtered out with a whitespace or embedded within the xml created

**Comment by kevmo314** [comment]
Do you have an example of a special character that causes problems? I'm aware of a couple that cause the XML document to be invalid, but I'm not sure of the best approach to handle them. It's not clear to me that filtering them out is a great idea...

**Comment by vaebhav** [comment]
Hi Kev,

Below is the example for a special character that causes problems

```
workbook = Workbook()

worksheet = workbook.new_sheet("Test1",data=["String1" , "String2" ,"String3" , "Sample String5 \x1a Sample"])

workbook.save("Unicode_test.xlsx")
```
The resultant excel throws an error , and upon checking the xml for the file, it is caused by the special character "\x1a" which is a box 

I also agree , filtering might not be the best solution for it , but in my case the entire result set was missing because of this character , hence I opted filter it.
